scheduler_bundle:
    transport:
        dsn: 'filesystem://first_in_first_out'
    tasks:
        billing_downgrade_expired:
            type: 'command'
            command: 'app:billing:downgrade-expired'
            expression: '0 0 * * *'
            description: 'Downgrade all expired subscription task'
            options:
                env: dev
