version: "3.8"

# Development environment override
services:
  php:
    volumes:
      - ./:/srv/api:rw,cached
      - ./docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # If you develop on Linux, you may use a bind-mounted host directory instead
      # - ./var:/srv/api/var:rw
    environment:
      APP_ENV: dev

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/api/public:ro

  blackfire:
    image: blackfire/blackfire:2
    depends_on:
      - caddy
    ports: ["8307"]
    environment:
        # Exposes BLACKFIRE_* environment variables from the host
        BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
        BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
        BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
        BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
        BLACKFIRE_DISABLE_LEGACY_PORT: 1

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
