monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: file_log # nested
            excluded_http_codes: [404, 405]
            # buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        # nested:
        #     type: stream
        #     path: php://stderr
        #     level: debug
        #     formatter: monolog.formatter.json
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
